local app={name='Files',icon='Files'}
function app.run(ctx)
 local d,u,i=ctx.disp,ctx.ui,ctx.input local path='/' local sel=1 local scroll=0
 local function items() local t={} if path~='/' then t[#t+1]={label='..',id='..',dir=true} end for _,n in ipairs(fs.list(path)) do t[#t+1]={label=fs.isDir(fs.combine(path,n)) and '['..n..']' or n,id=n,dir=fs.isDir(fs.combine(path,n))} end table.sort(t,function(a,b) if a.id=='..' then return true elseif b.id=='..' then return false end return a.id<b.id end) return t end
 local function draw(t) local w,h=d.getSize() u.clear(d) u.center(d,1,1,w,path,u.theme.highlight) local rows=math.max(1,h-5) for n=1,rows do local x=t[n+scroll] if x then u.fill(d,1,n+2,w,1,n+scroll==sel and u.theme.highlight or u.theme.bg) u.text(d,1,n+2,x.label,n+scroll==sel and colors.black or colors.white) end end u.button(d,{x=1,y=h-1,w=math.floor(w/2),h=2,label='Open'},false) u.button(d,{x=math.floor(w/2)+1,y=h-1,w=w-math.floor(w/2),h=2,label='Delete'},false) end
 local t=items() local function refresh() t=items() sel=u.clamp(sel,1,math.max(1,#t)) end
 while true do draw(t) local e=i.pull() if e.kind=='back' then return elseif e.kind=='touch' then local w,h=d.getSize() if e.y>=3 and e.y<h-1 then local n=e.y-2+scroll if t[n] then sel=n end elseif e.y>=h-1 then if e.x<=w/2 then local x=t[sel] if x then if x.dir then if x.id=='..' then path=fs.getDir(path) if path=='' then path='/' end else path=fs.combine(path,x.id) end refresh() else shell.run(fs.combine(path,x.id)) end end else local x=t[sel] if x and x.id~='..' then fs.delete(fs.combine(path,x.id)) refresh() end end end elseif e.kind=='move' then if e.dir=='down' then sel=u.clamp(sel+1,1,#t) elseif e.dir=='up' then sel=u.clamp(sel-1,1,#t) end elseif e.kind=='activate' then local x=t[sel] if x then if x.dir then if x.id=='..' then path=fs.getDir(path) if path=='' then path='/' end else path=fs.combine(path,x.id) end refresh() else shell.run(fs.combine(path,x.id)) end end end end
end
return app
