local app={name='Monitor Setup',icon='Monitor'}
function app.run(ctx)
 local d,u,i=ctx.disp,ctx.ui,ctx.input local s=ctx.settings local mode='screen' local sel=1 local mons={}
 local function scan() mons={} for _,side in ipairs(peripheral.getNames()) do if peripheral.getType(side)=='monitor' then local m=peripheral.wrap(side) local w,h=m.getSize() mons[#mons+1]={side=side,w=w,h=h} end end table.sort(mons,function(a,b)return a.side<b.side end) end
 local function draw() scan() local w,h=d.getSize() u.clear(d) u.center(d,1,1,w,'Monitor Setup',u.theme.highlight) local bw=math.min(30,w-2) local x=math.max(1,math.floor((w-bw)/2)+1) u.button(d,{x=x,y=3,w=bw,h=2,label=mode=='screen' and 'Select Screen' or 'Select Keyboard'},false) u.text(d,1,6,'Touch a monitor to select it',u.theme.muted) u.text(d,1,7,'Keyboard minimum: 20 x 12',u.theme.muted) for n,m in ipairs(mons) do local y=9+(n-1)*3 if y+1<=h-3 then local usable=m.w>=20 and m.h>=12 and m.side~=s.screenMonitor local chosen=(mode=='screen' and s.screenMonitor==m.side) or (mode=='keyboard' and s.keyboardMonitor==m.side) local label=(chosen and '[X] ' or '[ ] ')..m.side..' '..m.w..'x'..m.h if mode=='keyboard' and not usable then label=label..' unavailable' end u.button(d,{x=1,y=y,w=w,h=2,label=label},n==sel) end end u.button(d,{x=1,y=h-2,w=w,h=2,label='Done and Reboot'},false) end
 draw()
 while true do local e=i.pull() if e.kind=='back' then os.reboot() elseif e.kind=='resize' then draw() elseif e.kind=='move' then if e.dir=='up' then sel=u.clamp(sel-1,1,#mons) elseif e.dir=='down' then sel=u.clamp(sel+1,1,#mons) end draw() elseif e.kind=='touch' then local w,h=d.getSize() if e.y>=h-2 then os.reboot() elseif e.y>=3 and e.y<5 then mode=mode=='screen' and 'keyboard' or 'screen' draw() elseif e.y>=9 then local n=math.floor((e.y-9)/3)+1 local m=mons[n] if m then sel=n if mode=='screen' then s.screenMonitor=m.side if s.keyboardMonitor==m.side then s.keyboardMonitor=nil end ctx.saveSettings(s) elseif m.w>=20 and m.h>=12 and m.side~=s.screenMonitor then s.keyboardMonitor=m.side ctx.saveSettings(s) end draw() end end end end
end
return app
